services:

  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    hostname: webgrabplus
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 32M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA}/webgrabplus/config:/config
      - ${DATA}/tvheadend/wgp-data:/data
      - ${DATA}/webgrabplus/init:/custom-cont-init.d:ro
    networks:
      - pvr_default

networks:
  pvr_default:
    name: pvr_default
